### ISSUE TITLE
Wallet address changes for no clear reason

### ISSUE THREAD

**Issue by marcofranssen** [blockchain/My-Wallet-V3#223]
My wallet address has changed. (Web client and iOS client)
At first it was:
12f6NiQivUAineFpNG6iWr8jgxKij8pCYL
and now it is:
13n8Tk3GMXFfRTt39QEWk6DjGFLzJ77dzd

Why has this happened? Should I get worried? Is there a bug, or do we have a security matter here?

**Comment by alecalve** [comment]
If you are using the new wallet, it's totally normal. We now use [deterministic address generation](https://en.bitcoin.it/wiki/Deterministic_wallet) to improve your privacy.

**Comment by marcofranssen** [comment]
So my old and new address will both continue to keep working? As I have entered those in some other applications.

**Comment by alecalve** [comment]
Yes, you will receive payments to both addresses. Every time you receive a payment to a fresh address, we generate a new one for you to use. This allows you to receive payments without people knowing how much you received in total.
