### ISSUE TITLE
2FA broken

### ISSUE THREAD

**Issue by albysprx** [blockchain/My-Wallet-V3#229]
Why i don't receive 2FA sms anymore?? i can't login anymore...
the old wallet say when i click resend sms:
3 tentativi di accesso a sinistra
and the new wallet say:
Impossibile inviare SMS di verifica. (Failed to send verification SMS)

so the problem is blockchain, please fix it quickly i can't enter in my wallet!

**Comment by Sjors** [comment]
There might a temporary issue with SMS. Please submit a support ticket here so we can help you: https://support.blockchain.com/hc/en-us/requests/new
