### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by Informatic** [blockchain/My-Wallet-V3#281]
Just wondering. Is it supposed to be public and used by anyone besides blockchain.info employees? If that's the case, is there any public documentation of the API?

I'm just wondering if there is any field in Wallet object that says precisely how much funds can be withdrawn at current time. (balance without unconfirmed / doublespends)

**Comment by pernas** [comment]
This is not meant to be used by the general public. Hence, we don't have/maintain any public documentation. But, to answer your specific question, that field does not exist.
