### ISSUE TITLE
https://blockchain.info/upload_wallet -> 404 Not Found

### ISSUE THREAD

**Issue by tinoadams** [blockchain/My-Wallet-V3#286]
Importing your wallet via https://blockchain.info/wallet/import-wallet fails as https://blockchain.info/upload_wallet does not exist.

**Comment by mpfluger** [comment]
We have removed the feature to import Bitcoin-QT wallet.dat files. This will be reflected in the copy on that page shortly. It is still possible to import blockchain.info wallet.aes.json files.
