### ISSUE TITLE
How to request receive bitcoin payments API

### ISSUE THREAD

**Issue by almoharebh** [blockchain/My-Wallet-V3#316]
how to request receive bitcoin payments API in blockchain.info

**Comment by ferdi81** [comment]
Do I get helping about it

**Comment by ferdi81** [comment]
how to request receive bitcoin payments API in blockchain.info

**Comment by Aida43** [comment]
como funciona esta billetera

**Comment by jtormey** [comment]
See our Receive Payments API here: https://blockchain.info/api/api_receive

**Comment by Aida43** [comment]
esbilletera para recibir btc

2017-03-14 15:46 GMT-06:00 Aida43 <notifications@github.com>:
