### ISSUE TITLE
blockchainbdgpzk.onion/wallet/#/login says "Unable to establish session"

### ISSUE THREAD

**Issue by slrslr** [blockchain/My-Wallet-V3#325]
Hello,

last couple of days when i submit login form at https://blockchainbdgpzk.onion/wallet/#/login
via Tor Browser 6.5 (based on Mozilla Firefox 45.7.0), the page shows red blockchain warning bubble with text "Unable to establish session".
On the bottom of the page is "v1.11.10  (MyWallet v3.26.2)"
The https://blockchain.info/wallet/#/home does not have this problem and is running same MyWallet version.

**Comment by kristovatlas** [comment]
@slrslr thanks for letting us know. I can confirm the behavior. We're looking into it.

**Comment by mpfluger** [comment]
Thanks for the report - this should be fixed now. If you still experience issues, please re-open.
