### ISSUE TITLE
Wallet preferred for deposit

### ISSUE THREAD

**Issue by deno49** [blockchain/My-Wallet-V3#330]
1DVJp3FhKgmhUxARTkYTjiczFmQHiZrZKT1DVJp3FhKgmhUxARTkYTjiczFmQHiZrZKT

**Comment by deno49** [comment]
I'm sorry but I find blockchain a lot more complicated than I prefer. Would you kindly use the current wallet address I presented to deposit my funds? Once again, sorry for the inconvenience but I have been trying to receive my payment all day and I continue to fail. Please help! Dennis Collins

**Comment by deno49** [comment]
Any news on how I can receive my Bitcoin?

**Comment by kristovatlas** [comment]
Hi @deno49, please reach out to our support staff via https://support.blockchain.com/hc/en-us

GitHub is not the right communication channel for this problem.
