### ISSUE TITLE
HOW TO FIX THIS?

### ISSUE THREAD

**Issue by katlehotech** [blockchain/My-Wallet-V3#341]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

**Comment by jtormey** [comment]
`npm WARN` is just a warning, and generally doesn't need to be fixed. That particular warning seems to happen because the fsevents module isn't compatible with your operating system. Are there any other issues you're seeing?

**Comment by marinaannak** [comment]
isAwesome  Marina-ana2011@mail.ru
