### ISSUE TITLE
Forgot my blockchain app password 

### ISSUE THREAD

**Issue by Dferdi1199** [blockchain/My-Wallet-V3#343]
677316a3-1f5c-4776-a521-93c85e5a206a
ferdoferdi81@gmail.com

**Comment by Dferdi1199** [comment]
Forgot my password code

**Comment by Dferdi1199** [comment]
My address:-677316a3-1f5c-4776-a521-93c85e5a206a
My email 
ferdoferdi81@gmail.com

**Comment by jtormey** [comment]
Hi, Github issues are for software related problems / questions / concerns. If you forgot your password, please contact our excellent support team at https://support.blockchain.com, they might be able to help you.
