### ISSUE TITLE
Tor Browser 6.5.1, wallet does not work, only flashing squares

### ISSUE THREAD

**Issue by slrslr** [blockchain/My-Wallet-V3#364]
Hello,

when i submit login form at https://blockchain.info/wallet/#/login
(On the bottom of the Blockchain login page is: v1.13.13  (MyWallet v3.28.9))

via Tor Browser 6.5.1 (based on Mozilla Firefox 45.8.0) it take me into my account,
But the current exchange rate "1 BTC = " shows only flashing squares (means something like "loading")

Same three flashing squares are below "Most Recent Activity" and Transactions sub-page does not show any activity.

In the Firefox 52.0.2 (64-bit), all works without issue, but in Tor Browser is mentioned problem.

**Comment by mpfluger** [comment]
Please our .onion address:

https://blockchainbdgpzk.onion/

There is an intermittent issue, we're investigating.
