### ISSUE TITLE
Creating a blockchain wallet

### ISSUE THREAD

**Issue by braginlog** [blockchain/My-Wallet-V3#366]
Hello. I can not figure out how to create a blockchain purse using Javascript. Could you direct me in the right direction?

**Comment by Jenniferiuu** [comment]
I'm having problems to but I'm working on it I'll let you know wen I figure it out;)

**Comment by sherika36** [comment]
Me rto you have to do it step by step go info your web settings to privacy and pull up he actual  dialog to give your computer the commands to operate the software
[markdown-cheatsheet-online.pdf](https://github.com/blockchain/My-Wallet-V3/files/1025163/markdown-cheatsheet-online.pdf)
