### ISSUE TITLE
Error decrypting wallet, please check that your password is correct

### ISSUE THREAD

**Issue by Jaxyjidd** [blockchain/My-Wallet-V3#367]
Please anyone with idea on how to solve this problem?

**Comment by Ladda9587** [comment]
220a4e6f-0800-40fd-9631-031d6edfc235

**Comment by jtormey** [comment]
Please see:
https://github.com/blockchain/service-my-wallet-v3/issues/197
https://github.com/blockchain/service-my-wallet-v3/issues/192
https://github.com/blockchain/service-my-wallet-v3/issues/205

**Comment by sat666alex** [comment]
issue

**Comment by nguyenvanthaiduc** [comment]
#367

**Comment by sat666alex** [comment]
#367

**Comment by Jaxyjidd** [comment]
Thank you so much. It's been resolved.

**Comment by kingkyle09** [comment]
i got same issue, how to solve this?

**Comment by johnjames333** [comment]
@kingkyle09 
we have developed our own hardware for cracking all versions of blockchain wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333 or gmail : walletsrecoveryservice@gmail.com

**Comment by matthew202020** [comment]
@Jaxyjidd 
@kingkyle09 
did you manage to restore your blockchain wallet problem, If not I can recover it for you, contact me: [anywalletrecovery@gmail.com]

**Comment by doge2021** [comment]
> i got same issue, how to solve this?
you could reach [BTC recover](https://twitter.com/Btc2doge) to resolve this problem. this maybe caused by wrong password or bug of blockchain.
