### ISSUE TITLE
blockchain.wallet.v3

### ISSUE THREAD

**Issue by BangLy** [blockchain/My-Wallet-V3#386]

**Comment by sherika36** [comment]
Yes

**Comment by sherika36** [comment]
Bitcoin Wallet (Android)
![wallet_help](https://cloud.githubusercontent.com/assets/28791442/26643256/9e6879c0-45e5-11e7-9561-d2c20c00d84a.png)
![wallet_menu_mobile](https://cloud.githubusercontent.com/assets/28791442/26643277/b5319290-45e5-11e7-93a8-e828a38c5052.png)
![wallet_menu_desktop](https://cloud.githubusercontent.com/assets/28791442/26643308/c1b1ae92-45e5-11e7-9e41-d3567860bda1.png)
![wallet_menu_hardware](https://cloud.githubusercontent.com/assets/28791442/26643315/c9e451aa-45e5-11e7-9879-4e27e813b167.png)
![wallet_menu_web](https://cloud.githubusercontent.com/assets/28791442/26643422/20228816-45e6-11e7-9fb4-95d996df4430.png)

**Comment by htoohtetaung** [comment]
Yea

**Comment by deancameron119** [comment]
Nhb

**Comment by deancameron119** [comment]
Yes
