### ISSUE TITLE
Frozen money

### ISSUE THREAD

**Issue by szadou77** [blockchain/My-Wallet-V3#400]
Hi
I pushed Receive button. Got address. On this address i send money. And ? Nothing !
Wallet is only blinking with squares everywhere. When I push transaction ? Empty
But money reached that address. Over 30+ confirmations.
When I push Send ? Blinkin' dots .... I can see my money only in : My wallet-> used addresses.
How to get them back ? how to send them to another adress ? 
PLease help

**Comment by verdade8500** [comment]
Pra quem entende vai bem,mas quando não se entende nada da certo ,???      minha carteira   WMID:325667510034 minha carteira  puxar todos os bitcoins nessa carteira

**Comment by jtormey** [comment]
This doesn't seem like an issue with this API library. If you have a problem with your wallet, please reach out to us at https://support.blockchain.com

**Comment by szadou77** [comment]
Problem solved. Thank you 

21. Czerwiec 2017 21:36 od notifications@github.com:
