### ISSUE TITLE
Bitcoin 

### ISSUE THREAD

**Issue by verdade8500** [blockchain/My-Wallet-V3#409]
Ola quero que os bitcoins estão aonde que nem eu sei dos meus ganhos que fim levou os meus bitcoin/

**Comment by tracihaire** [comment]
They say bitcoin s is bit going to be here to much longer

**Comment by sherika36** [comment]
Don't believe everything you hear until their is solid proff this subject doesn't need to be discussed or brought up for that matter, with all due respect please enjoy your day

**Comment by kuanlim** [comment]
Thanks

**Comment by AIKKYU** [comment]
#409

**Comment by shakilmia** [comment]
I can't understand
