### ISSUE TITLE
How to claim Bitcoin Cash for BTC stored in a Blockchain.info HD Wallet?

### ISSUE THREAD

**Issue by tonesnotes** [blockchain/My-Wallet-V3#416]
The community badly needs a procedure for accessing the Bitcoin Cash they now own tied to addresses managed by blockchain.info HD wallets.

I'm posting this as an issue to the repository because there doesn't appear to be any other channel open.

**Comment by tuchik** [comment]
****

**Comment by jtormey** [comment]
We don't have support for sending / receiving Bitcoin Cash at the moment. To send Bitcoin Cash from your blockchain.info wallet, you can use your backup phrase / private keys in a different wallet that does support it.

**Comment by crisjay2126** [comment]
Here my nos,639163050372  ref.121218246

**Comment by raisty** [comment]
Seems very old blockchain wallets doesn't work even with backup phrase / private key.
Can you check it?

**Comment by tracihaire** [comment]
I try and put ur address in the wallet and it will not let u said Mooney in order to put in wallet so how r u supost to have money in wallet if it won't let u put it thete

**Comment by tracihaire** [comment]
Put bit in usi tech

**Comment by tracihaire** [comment]
How do u put ur bit in a paper  wallet

**Comment by mikeyjoe** [comment]
Paper wallet don't have one I'll grab one

**Comment by plondon** [comment]
Full BCH support has been added
