### ISSUE TITLE
Account Access Recovery is Broken

### ISSUE THREAD

**Issue by tonesnotes** [blockchain/My-Wallet-V3#417]
I have two accounts that I can't access.

I have the identifier and password for both accounts.

In one case (90f8dfdd-454b-40dd-9f9a-d77bc45f6a25) the login verification e-mail never arrives. Attempting to change the e-mail address associated with the account appears to work (the reset e-mail arrives at one of the possible addresses associated with the account), but nothing changes even after attempting to reset the e-mail to a known working address.

In the second case (e48f760b-41a7-4013-aec9-c35e494e71e8), Google Authenticator is no longer available and resetting 2FA appears to complete successfully but login still prompts for a Google Authenticator code.

I'm posting this issue to the repository because I can't find a more appropriate(?) support channel to use.

**Comment by crisjay2126** [comment]
Hello

**Comment by mpfluger** [comment]
Please reach out to our support team:

https://support.blockchain.com/hc/en-us/requests/new

**Comment by johnjames333** [comment]
@tonesnotes 
if you haven't solved your account problem
I can recover it you

**Comment by marlando20** [comment]
@tonesnotes 
did you get access to your blockchain wallet problem, If not I can restore your wallet for you, contact me: anywalletrecovery@gmail.com
