### ISSUE TITLE
404 broken link in README.md

### ISSUE THREAD

**Issue by alexprut** [blockchain/My-Wallet-V3#460]
In file `README.md` last line:
Bug Bounty: https://www.crowdcurity.com/blockchain-info link is broken (404 page not found)

**Comment by kristovatlas** [comment]
@alexprut thanks -- the correct link should be https://hackerone.com/blockchain

**Comment by alexprut** [comment]
PR in https://github.com/blockchain/My-Wallet-V3/pull/497
