### ISSUE TITLE
Did I get scammed? HELP!!

### ISSUE THREAD

**Issue by rosie693** [blockchain/My-Wallet-V3#476]
I was friend-ed by a guy on Linkedin and he asked if wanted t get involved in Bitcoin. I had been reading a lot about it and thought I would give it a shot. He said that if I funded my wallet in Blockchain with a minimum of 0.1 BTC he would mine it for me. He said I would have a return of 0.3 BTC within 48 hours.  He had asked me what kind of goal I had for my return and I told I asked him if $40k a month would be possible and he said he would try. Putting up the $1500.00 USD was a bit of a stretch as I am on disability and he knew this. He started the mining process and I was led to believe all was going well but he tells me know that since he had to raise the Hash_______?? that the antminer was requesting for more funding to a tune of 0.2 BTC more...about $4k today's price.  He tells me now that he will release the coin back to my wallet but I will not be able to withdraw it until I come up with the 0.2 BTC and once I fund that I can withdraw all of it them. Still waiting on the return of the coin to my wallet but thinking he threw the screws to me. 
Anyone know how to verify this and his information and is there anyway to do some type charge back similar to bad transactions with credit cards?
HELP!!

**Comment by jesobreira** [comment]
Bitcoin transactions are irreversible.

Anyway, this area is for posting issues related to MyWallet library. For such inquiries, please try [BitcoinTalk](https://bitcointalk.org) or [Bitcoin at StackExchange](https://bitcoin.stackexchange.com/).
