### ISSUE TITLE
(Help!) Partial Spend from a cold wallet sent to a change address without PK

### ISSUE THREAD

**Issue by Janju** [blockchain/My-Wallet-V3#478]
Hello friends, I need help on an important issue.

I keep most of my funds in a cold wallet, generated in bitaddress.org (Offline), when I want to spend these funds, I enter the private address in Blockchain.info on Settings > Address > Import new address.

After that, I send the amount I want for some exchange, and return the change (Rest of funds) to another cold wallet, that I generate in bitaddress, entering in blockchain the public key of the same to follow the balance, I have been doing this for a long time and I never had problems.

But last time on the transaction screen, I noticed that below of Watch-Address field of the cold wallet, there is a Private Key field, which has decreased the job of inserting it in the option menu a new address to spend the funds.

![1](https://user-images.githubusercontent.com/7645206/34235028-0e8b2a96-e5d6-11e7-9820-3113b8761912.png)

I decided to enter the private key of my cold wallet in this field, and sended a portion of my funds to the exchange, imagining that the change, would be re-sent to my default wallet of blockchain, but that was not what happened, these funds are sent to an address which was added as 'Watch-Only' address, and that I do not own the private key.

![3](https://user-images.githubusercontent.com/7645206/34235030-0ec882ec-e5d6-11e7-8e94-bd34b6dc16d5.png)

The money sent to the exchange has arrived correctly, but the change of my funds are stuck in a unknown address.

Address of cold wallet: [1AXXCct4QATf2UdX92piw1AA2As8AoZaoM](https://blockchain.info/address/1AXXCct4QATf2UdX92piw1AA2As8AoZaoM)

Exchange address (Correctly sent): [1PjcZKMFR8wkFjoMAE2aoVfSeB5xHwVLdu](https://blockchain.info/address/1PjcZKMFR8wkFjoMAE2aoVfSeB5xHwVLdu)

Change address (Stuck funds): [1KfTVrLG376B7SYb1bA6NnY7KyK825T72B](https://blockchain.info/address/1KfTVrLG376B7SYb1bA6NnY7KyK825T72B)

![2](https://user-images.githubusercontent.com/7645206/34235029-0ea993f0-e5d6-11e7-8719-58bd83374866.png)
I believe it was not malware, since the funds were sent to the exchange correctly, otherwise, the entire balance would have withdrawned to some other address.

I am a developer and started to study your code to understand how the process of generating the change address is done in the case of a partial spend, but this will take a while.

I'm using this tool: [https://iancoleman.io/bip39/](https://iancoleman.io/bip39/) (Offline) trying to discover the private key of the address: 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B but apparently it is not part of my HD wallet, or it is in some child node that I can not find.

These addresses are part of the transaction after the cold wallet address, and are contained in the HD nodes (Internal and External):

[141rWhPaeSpTqn2YH1fw2WFnwhojQTERyp](https://blockchain.info/pt/address/141rWhPaeSpTqn2YH1fw2WFnwhojQTERyp)
![4](https://user-images.githubusercontent.com/7645206/34235031-0ee5fc28-e5d6-11e7-8684-792a3f1b5080.png)

[1LsLpbPNS2w98WnKbQ2MmubkQBWhxbPvrz](https://blockchain.info/pt/address/1LsLpbPNS2w98WnKbQ2MmubkQBWhxbPvrz)
![5](https://user-images.githubusercontent.com/7645206/34235032-0f0332c0-e5d6-11e7-8d10-af5eccfe2ba8.png)

Please, I ask this team to help me because these are all savings I have, I'm very worried and ready to help them and begin to collaborate with the project independent of the outcome, including to correct this problem.

Thanks for all your help!

**Comment by pernas** [comment]
If I understood that correctly, the explanation and images you attach there, are suggesting that you spent money from this watch only address 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B and the change went to the same watch only address as it must go. You scanned the private key from that address at the spending moment. The address is still a watch only address because the key does not get imported when you spend from watch only.

This is your transaction:
https://blockchain.info/tx/7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3
 and the change is correctly placed to the address you spent from and obviously you have the private key.

**Comment by pernas** [comment]
On the other side, I highly discourage you to use bitaddress generated addresses and all this workflow moving around private keys. I would use the hd wallet.

**Comment by Janju** [comment]
Hello pernas, first of all sorry for my bad english.

The address of my cold wallet where my funds are, and was like Watch-Only in the blockchain, was this: 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM, I entered the private key of this address to make a partial spending in the field mentioned above, and after confirming the transaction, this address was changed by: 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B, which I imagine be a change address generated by blockchain, and obviously the private key of 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM does not work on it, and I didn't created it anywhere.

Now that you have explained, I understand that the wallet not save my private key, doing the transaction and keeping the address Watch-Only, however like you said, the funds should remain on: 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM, but it not happened.

If this address was spent, your private key exists somewhere, my question is if, it was generated from my seed otherwise I will be very worried.

**Comment by pernas** [comment]
The transaction that you did it is not moving money from 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM.

You moved money from 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B. 

Read it again: https://blockchain.info/tx/7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3
Hence, you did not moved the money from the cold wallet that you think you used. 

I suspect that you have a private key and "1KfTVrLG376B7SYb1bA6NnY7KyK825T72B" is the compressed address and "1AXXCct4QATf2UdX92piw1AA2As8AoZaoM" is the uncompressed address and you are getting confused.

**Comment by Janju** [comment]
Let's take steps:

1 - The balance was sent from the address of my cold wallet 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM to the address: 1LsLpbPNS2w98WnKbQ2MmubkQBWhxbPvrz:
![image](https://user-images.githubusercontent.com/7645206/34265405-e9eb67e6-e65c-11e7-8dba-34c150683b1e.png)
[Transaction: bbaea71431632ea9c3f16d76ee9aa3c5f1f0f5343d8896d277d9771d3744f881](https://blockchain.info/pt/tx/bbaea71431632ea9c3f16d76ee9aa3c5f1f0f5343d8896d277d9771d3744f881)

2 - This Address: 1LsLpbPNS2w98WnKbQ2MmubkQBWhxbPvrz, exists in the HD Wallet seed external key list, and has two outputs:
![image](https://user-images.githubusercontent.com/7645206/34265414-f41b9cb8-e65c-11e7-900a-f2058f8eef19.png)
[Transaction: 7e740f881d73e463def7bc1d097be072d7f0e17990ca71aadac8e19611096427](https://blockchain.info/pt/tx/7e740f881d73e463def7bc1d097be072d7f0e17990ca71aadac8e19611096427)

3 - From these two outputs, the address: 141rWhPaeSpTqn2YH1fw2WFnwhojQTERyp, is contained in the list of internal keys of the HD wallet, and finally sends the funds to the address: 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B:
![image](https://user-images.githubusercontent.com/7645206/34265419-f97acb5c-e65c-11e7-88f0-0ecd1ee1cd17.png)
[Transaction: 4f17048311d2628f78f3c51cbd1506b9e83424696f3fc67f5939d56f024c6c9f](https://blockchain.info/pt/tx/4f17048311d2628f78f3c51cbd1506b9e83424696f3fc67f5939d56f024c6c9f) 

4 - And finally, the output 1PjcZKMFR8wkFjoMAE2aoVfSeB5xHwVLdu partially sends the funds to the exchange and the rest to himself:
![image](https://user-images.githubusercontent.com/7645206/34265427-feb483f6-e65c-11e7-9f6a-7b449b2542bc.png)
[Transaction: 7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3](https://blockchain.info/pt/tx/7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3) 

I am not a deep connoisseur of the hierarchical key generation process, I have been studying intensely since this problem occurred, I have tried to enter the private key of the address: 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM in this bitaddress.org option above, trying to get the compressed keys and see if the address: 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B is in fact a compressed public key derived from the private key of the address 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM, but it has not been returned.
![image](https://user-images.githubusercontent.com/7645206/34266150-57ffbcbc-e65f-11e7-8979-7c90cec2f6bb.png)

How can I get the compressed keys (WIF, I'm not sure), from the address of the cold wallet 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM?

If this address 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM was obtained through bitaddress.org, does it return an uncompressed key?

**Comment by Janju** [comment]
Just for curiosity, I put the PK of 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM and then returned this:

![image](https://user-images.githubusercontent.com/7645206/34268750-096c165e-e669-11e7-8b6e-4402f5ff84da.png)

Both private keys WIF - 51 characters starting with number 5, and my compressed PK with 52 characters, works with 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B.

**Comment by Janju** [comment]
Just for curiosity, I putted the PK of 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM in the Wallet Details of bitaddress, and the public key (Not compressed I think), is: 1G9kvwV2KHmFEQ5FnNKt8jzxkM2pRMFPwb.

![image](https://user-images.githubusercontent.com/7645206/34268957-cd12433a-e669-11e7-948b-583fb14e631f.png)

Both private keys, WIF 51 chars base58 and WIF compressed 52 chars base58 (The PK that I have of 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM), don't work with 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B.

**Comment by Janju** [comment]
Another fact, in the Private Key screen of 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM, the Base58 format returning me a address that starts with 4, and I can't reach this address in the bitaddress wallet detail tool.

Maybe, the key 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B is coming from this Base58 key?

![image](https://user-images.githubusercontent.com/7645206/34271176-53cd2504-e672-11e7-982e-5863cc5c267b.png)

I also tried inserting my seed into the BIP38 Passphrase option, which returned a private key started at 6, I put it in the private key field of 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B, which asked me for the password of my seed, when put also did not work.

![image](https://user-images.githubusercontent.com/7645206/34271269-b45686e0-e672-11e7-9551-80cfe8a63b64.png)

**Comment by Janju** [comment]
Another fact, in the Private Key screen of 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM, the Base58 format returning me a address that starts with 4, and I can't reach this address in the bitaddress wallet detail tool.

Maybe, the key 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B is coming from this Base58 key?

![image](https://user-images.githubusercontent.com/7645206/34271385-3aab8cea-e673-11e7-8a7a-c3f02effc0e4.png)

I also tried inserting my seed into the BIP38 Passphrase option, which returned a private key started at 6, I put it in the private key field of 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B, which asked me for the password of my seed, when put also did not work.

![image](https://user-images.githubusercontent.com/7645206/34271412-575dc574-e673-11e7-8978-38d91c8898e4.png)

**Comment by pernas** [comment]
Well, Here there is one true fact. You own the private key corresponding to 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B because you did a transaction spending money from it.

When you have money on your hd wallet you don't have to handle the addresses by yourself. Actually, I suspect that you may have imported one of your own hd-addresses as watch only.

I mean:

If 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B is part of AccountX and you import "1KfT..." as a watch only address. You will be able to select "1KfT..." to spend from watch only but you will need to scan the key. But if you select spend from AccountX you will be able to move the same money properly.
As I said, you should be using the HD-wallet and only not using the import feature at all, unless you know what you do. You must no import your own (hd) addresses.

**Comment by Janju** [comment]
Well, you did not understand anything I said, this is not an address on my HD wallet.

But okay, I'll run the project locally and find out how this address was generated, thank you.

**Comment by pernas** [comment]
Sure, => support team <=

**Comment by jtormey** [comment]
There seems to be a misunderstanding, this wallet does not generate any addresses outside of the HD structure.

If an address is in the Imported/Watch-only section of the wallet, the only way it could be there is if you intentionally import the address or private key from another source.

What makes you think this address was created by your Blockchain Wallet?

**Comment by Janju** [comment]
@jtormey , if you read all that I posted with patience, you can understand that.

I usually use yours wallet just to spend my cold wallet funds, instead of importing the private key from my address (Cold Wallet) through Settings > New Address, I used the Private Key field of the spending screen, and I did a partial spent of my funds.

Instead of these funds have been sent back to my default wallet in blockchain (Path 0), it was sent to a third address that is not compressed or decompressed from the private key of the original address (Cold Wallet Address).

But this is not a malware, because the funds have been sent to the exchange arrived correctly.

I'll have to do a brute force on my seed and see if it has landed in some distant galaxy on the paths of BIP44.

If you that have developed can not help me, then no one can, and I just lost all my investment for a possible bug on the change address.

I'll appreciate it if you can review this with me, otherwise, I'll have to learn how the wallet works inside, and maybe I'll get my funds back one day, for all the files that are part of generating addresses, payments, and so forth, I see your name there.

Thank you anyway, because this little balance is all I have.

**Comment by jtormey** [comment]
Could you explain how you created this transaction? https://blockchain.info/tx/7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3

If you were able to spend from 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B before, why are you unable to now?

**Comment by Janju** [comment]
Because this is the first transaction: [bbaea71431632ea9c3f16d76ee9aa3c5f1f0f5343d8896d277d9771d3744f881](https://blockchain.info/pt/tx/bbaea71431632ea9c3f16d76ee9aa3c5f1f0f5343d8896d277d9771d3744f881)

Not this: [7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3](https://blockchain.info/tx/7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3)

I wanted to sent a portion of my funds from 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM to 1PjcZKMFR8wkFjoMAE2aVfSeB5xHwVLdu, and all the intermediary transactions of this process, created by the blockchain until it reaches 1PjcZKMFR8wkFjoMAE2aVfSeB5xHwVLdu, including the address 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B (I've never seen it).

I put below a picture. that shows exactly what I did when spent this funds:
![image](https://user-images.githubusercontent.com/7645206/34276174-60e4171a-e687-11e7-9ecd-4dfc43fb168d.png)

After do this, the 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM turned in 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B.

In this history at 14 December, the address that was here is 1AXXCct4QATf2UdX92piw1AA2As8AoZaoM, and after this spent, turned in 1KfTVrLG376B7SYb1bA6NnY7KyK825T72B, like the wallet changed the address:
![image](https://user-images.githubusercontent.com/7645206/34276234-a2626b38-e687-11e7-8bdc-f607bc214ff5.png)

**Comment by Janju** [comment]
And the addresses that are in the middle of transactions, exists in the HD wallet lists (External and Internal):

![image](https://user-images.githubusercontent.com/7645206/34276677-946965de-e689-11e7-967b-99fbdfe5d140.png)

![image](https://user-images.githubusercontent.com/7645206/34276684-9730df86-e689-11e7-9475-16c85919ff82.png)

See the intermediary transactions between [1AXXCct4QATf2UdX92piw1AA2As8AoZaoM ](https://blockchain.info/address/1AXXCct4QATf2UdX92piw1AA2As8AoZaoM)and [1KfTVrLG376B7SYb1bA6NnY7KyK825T72B](https://blockchain.info/address/1KfTVrLG376B7SYb1bA6NnY7KyK825T72B).

**Comment by pernas** [comment]
This is absurd. The wallet:
- do not send intermediary transactions by itself
- do not send money to random derivations somewhere far away in the galaxy

And the funnier part is that you claim that you were spending money from "1AXX" but the reality, as the transactions shows is that you spent from "1KfT.." and send the change to "1KfT...". This is a joke.

**Comment by Janju** [comment]
@pernas, what can I do if you can trust me?

This is the print generated by bitaddress of '1AAX'

![image](https://user-images.githubusercontent.com/7645206/34276810-359b1380-e68a-11e7-8a0c-3c89eaceb853.png)

**Comment by pernas** [comment]
This image does not proof anything.

You created that transaction:
https://blockchain.info/tx/7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3

You did that because this transaction is sending the money where YOU WANTED TO send the money. And the change CAME BACK to ORIGIN. This is the expected behaviour of the wallet and it is a PROOF that you can spend from "1Kft...". Hence, as I said, you are confused and this is not a bug.

**Comment by Janju** [comment]
I just want to understand, why you think I would be here wasting so much time on it, at what cost?

I was not wrong, I am a developer and not a curious, the problem was generated by the wallet, if you can not help me, I will try find out where the error is, and where this last transaction is created, and I hope can fix it.

**Comment by Janju** [comment]
Timeline

![image](https://user-images.githubusercontent.com/7645206/34277212-f2e322ce-e68b-11e7-9145-0b979ae72eec.png)

**Comment by pernas** [comment]
Do you realise how absurd is this situation?

You claim that you did a payment to an exchange. This payment corresponds to that transaction:
https://blockchain.info/tx/7b506a1623eb4edc0d10b221c8abc84e2f1c8b59b425cde566dc16b7c25bbdf3

The tx contains 1 input from the address "1k..". Hence you spend btc from that address. But you claim that this is a watch only address that you don't control. But somehow, you spent btc from it.
Then, the outputs are two. One for the exchange and the other one for the change coming back to "1k..".

**Comment by Janju** [comment]
I do not want to fight or even say that the wallet comited a mistake, I just want to understand what happened.

I did not spend anything from the 1KftT.., because this address was never generated by me, the order of things is as I said several times above, what happened in this last transaction I have no idea.

What exactly I did, is this: 
![image](https://user-images.githubusercontent.com/7645206/34277446-df10fdc4-e68c-11e7-80d9-95b2ae8cd57b.png)

**Comment by pernas** [comment]
Amazing, then you found a way to make payments spending money from addresses that you don't control the private key. When you find that "bug" please explain me how you did that, because you broke bitcoin.
