### ISSUE TITLE
how get blockchain.info API key 

### ISSUE THREAD

**Issue by wzzjhc** [blockchain/My-Wallet-V3#494]
https://api.blockchain.info/customer/signup

I AM wating many days....

**Comment by plondon** [comment]
I will reach out to our team that distributes api keys. Thanks

**Comment by wzzjhc** [comment]
my email wzzjhc@gmail.com

**Comment by Bang631** [comment]
My email bangly631@gmail.com

**Comment by Ruethairat** [comment]
Ruethairatkaeokunsri@gmail.com
