### ISSUE TITLE
https://blockchain.info/payment_request?address=1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp&message=https://blockchain.zendesk.com/home&amount_local=400&currency=USD&nosavecurrency=true

### ISSUE THREAD

**Issue by Arafathkobir** [blockchain/My-Wallet-V3#515]

**Comment by yousifyou** [comment]
What is this for?  Please explain iw can I request a payment?

**Comment by isbague** [comment]
How to used my wallet?

**Comment by yousifyou** [comment]
Re: [blockchain/My-Wallet-V3]
https://blockchain.info/payment_request?address=1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp&message=https://blockchain.zendesk.com/home&amount_local=400&currency=USD&nosavecurrency=true
(#515)

**Comment by sale7-778** [comment]
😍

**Comment by lillemon** [comment]
193R4SKhoogep6UgDJZpmQcQh7irhi6Fn5
